### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by mfsi-subhranil** [Giorgio003/Youtube-TV#11]
Hi  Giorgio003,

Thanks for your wonderful code, but i am getting an error with new code. I have a youtube channel which was working perfect with v2 API but once i upgrade using yours i am getting below error

userInfo.items[0] is undefined
settings.playlist = userInfo.items[0].contentDetails.relatedPlaylists.uploads;
ytv.js (line 214, col 24)

Can you please help me to trace this issue.

Thanks

**Comment by mfsi-subhranil** [comment]
I figured it out using Channel ID instead of User ID

**Comment by Giorgio003** [comment]
Channel ID (`UCxxxxxxxxxxxxxxxxxxxxxx`) will be used over User ID. I added both, as older accounts will still be able to use User ID, where as new accounts are limited to Channel ID. APIv2 did accept both Channel ID and User ID under the same field, but APIv3 splits them into separate fields. Example `id=` vs `forUsername=`:

``` javascript
// From prepare.build to determine the correct ID for userInfo (channel) query
if (settings.channelId){
    settings.cid = 'id='+settings.channelId;
} else if(settings.user){
    settings.cid = 'forUsername='+settings.user;
}
```

Currently I have Channel ID override if both are set because Channel ID is also used to get user playlists (with no User ID/`forUsername` option for that query). There might be a better way to go about this like parsing to match the starting `UC` and the 24 character length for Channel ID's (assuming they're fixed to 24 characters).  
For now I'll look into making the documentation clearer on Channel ID's vs User ID's as well as remove some redundancies and organize the options in a better layout. Might add some console logs as well to help with more meaningful error codes to help with troubleshooting.
