### ISSUE TITLE
Playlist on bottom

### ISSUE THREAD

**Issue by zevero** [Giorgio003/Youtube-TV#14]
How is this done?
Specifically I'd like to have the playlist on bottom responsively if the width is not sufficient.

**Comment by Giorgio003** [comment]
Currently in the responsive design it's set to after a certain width (992px which that number was based on a bootstrap layout switch at that resolution) which appears on this line in `ytv.js`:
`+'@media only screen and (max-width:992px) {'`
Some other responsive layouts may use different transition width so that number can be modified to match. 

Assuming you have `responsive: true` setting to enable the dynamic re-sizing as the original Youtube-TV didn't have responsiveness so the default is false. I may change the default to true in the future as most sites now-a-days should be responsive in some way; but I figured anyone using the project from before in a static configuration would have no issues switching.

**Comment by zevero** [comment]
Thank you for your detailed response. This helped me to find the problem:
I was using the jquery method $('#myvideo').ytv(settings); and the generated css you mentioned was not valid because id is an HTML Element instead of the id of the element.

Please change line 525 of ytv.js from

```
new YTV(this, options);
```

to

```
new YTV(this.id, options);
```

Now everything is working fine!

**Comment by Giorgio003** [comment]
No problem and thanks for pointing this out! I must have missed this as the jQuery demo doesn't use the `light` theme or `responsive` option (and accent would default to white).

So thanks again, I've added it along side my recent update allowing multiple playlist id's in `playlist: ''`.
