### ISSUE TITLE
The player doesn't work, not even the demos

### ISSUE THREAD

**Issue by bencuri** [Giorgio003/Youtube-TV#20]
I have downoaded this package to replace the old one that used the GOOGLE API V2. The problem is I followed the instructions, but what I can see is only a blank screen. The same applies to the demos. Are you sure Youtube didn't change something again that makes the player unable to display channel contents?

**Comment by Giorgio003** [comment]
Is there anything outputted into the Console Log for the browser? Recently added some lines the other day to allow errors from the API to pass through into the console log to help with troubleshooting.

Also if you're testing the demos from downloaded package the API key would need to be swapped as well as the key used in the demos is restricted to the githib.io links in the readme. (demos use `./demos/assets/ytv.js` instead of `./src/ytv.js`)

**Comment by bencuri** [comment]
The log says this: "Failed to load resource: the server responded with a status of 410 (Gone)"

Then it gives a link: "http://gdata.youtube.com/feeds/api/playlists/PLgfVOzkL_0SObEimLtHdRL5zIdTHfoc5l?v=2&alt=json&format=5&max-results=50" 

This page does not exist.

I have swapped the key in the demo, but no use. I also tried replacing user with channelID, but that doesn't work either.

**Comment by bencuri** [comment]
I have an additional Youtube channel for my Google account. So I have the account with the username I opened my google account with, and there is an additional channel created. I use the latter one to upload videos to. Is it possible this makes the confusion? If you have multiple Youtube channels for 1 Google account, can they be accessed with the same API key?

**Comment by bencuri** [comment]
Oh, I have found the source of problems. The Youtube Data API was not turned on. When I opened the panel in Chrome, it failed to load, and I forgot to check the status later.

**Comment by Giorgio003** [comment]
Hmm well first thing I noticed is `gdata.youtube.com` is the old API v2. The current API v3 uses `https://www.googleapis.com/youtube/v3/`. So if you recently switched out the old version of Youtube-TV it's possible the browser could still be using the cached version of `ytv.js` a quick `Ctrl+F5` should clear the cache and refresh.

I just tested using the playlist ID in the link you sent above and it worked for me. (Side note, it is possible to just use `playlist: 'playlist_id'` as it will automatically fill in the user if no `user` or `channelId` were given).

As for separate Youtube and Google channels I believe each should different channel IDs.

API turned on might help haha :) Odd though, that should've sent some kinda error back to the console regardless. I'll do some tests to see what API throws back if disabled.

**Comment by Giorgio003** [comment]
*with the exception of IE8-10 doesn't have the API errors pass through as it's using `XDomainRequest` instead of `XMLHttpRequest` which does not allow access to readyState's and status codes. 

Did a quick test with an API disabled using Chrome:
![api_disabled_test](https://cloud.githubusercontent.com/assets/1957101/8070038/815c7428-0ecc-11e5-90dd-af04625b7e74.png)

**Comment by mvmkr** [comment]
Hi. I noticed that the script generate loads of errors in chrome console, but nevertheless it works if i use my generated ApiKey and users from provided demos. If i set my user, it shows just the blank screen.

So users : 'Apple', 'theonion', 'collegehumor', 'GoogleDevelopers', 'googlefiberofficial' wich are used with demos works in combination with my ApiKey and my playlist. When i change the user to my user, it doesn't load nothing, and my user is a bunch of digits, automatically generated by google.

Hope this info help to solve issues. As i really like this script and use it on few sites which now are not fully functional due to youtube api update :(

**Comment by TheElectroclassics** [comment]
Here, it doesn't work. Neither the demos, nor my html. I grabbed my Public API Key, disabled every API but the YouTube one, and nothing comes. I really need it to work. It doesn't work, even locally

**Comment by Giorgio003** [comment]
@mvmkr in regards to the `chrome-extension` errors unfortunately are related to Youtube and the Google Cast/Chromecast extentions, or lack of. If you go to any video on `youtube.com` you will see similar error's. I have been following this issue (https://code.google.com/p/google-cast-sdk/issues/detail?id=309) for awhile now which seems to be low priority for them.  

The generated digits should go under `channelId: ''` instead of `user: ''`.
In the [testing.html](http://giorgio003.github.io/Youtube-TV/demos/testing.html) I have the channel ID as well, just commented out in the current version.  
So in the case of `googlefiberofficial` their channel ID is `UCg44zX42-GjMr5XqyK3RmsQ`
`user: 'googlefiberofficial',` **=** `channelId: 'UCg44zX42-GjMr5XqyK3RmsQ',`  

Additionally in your case you could just specify the `playlist: ''` and it should automatically fill in the corresponding user of the playlist. :)  

As for @TheElectroclassics for testing locally you would want the referrers set to allow any referrers (or IP address). Example:
![referrer](https://cloud.githubusercontent.com/assets/1957101/8140790/0d895c4c-112d-11e5-956a-4fe6483737a7.png)  

And for @bencuri I believe he sorted out his issue which was the API wasn't enabled. :) So I will close this issue #20 after you two are able to get your projects in working order.

**Comment by bencuri** [comment]
Yes, my issue has been solved by setting the Youtube Data API setting to ON in the control panel of the developer console of Google, so the thread starting issue no more prevails.

**Comment by mvmkr** [comment]
I got everything working. Very handy and useful script. Why don't you create a WP plugin, it can be very popular.
Thx for help!

**Comment by TheElectroclassics** [comment]
Sorry, but mine still broken, here's the page in my server:
http://the-electroclassic.com.mx/YTV/testing.html
I know that in order to make it work locally you need to remove all the servers from the panel, but nothing comes :(

**Comment by Giorgio003** [comment]
@bencuri Thanks for the reply! :)

@mvmkr good to hear! I originally started on this project when I was looking for a simple video gallery for a portfolio site I was putting together then started to add in features I was looking for, for that site. Additionally I noticed the original creator had moved on to other projects after the depreciation of APIv2 back in 2014, and with the cut off date approaching (April 20th 2015) I knew I'd have to rewrite the project to work with the newer APIv3 or else look for alternatives. 
So I'll definitely look into creating a WP plugin in the future!  

@TheElectroclassics I took a look at the link you provided and got this message in the console:  

```
Youtube-TV Error: Youtube API Response: ipRefererBlocked
Details: There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.
```

So this would be related to the referrers you have currently set. After some further investigation I believe the `Browser Key` doesn't allow IP Addresses as referrers. So depending on how you're testing locally.  
If you're testing as a local server (ie. `localhost/.../YTV/testing.html`) you can set the following for referrers:

```
the-electroclassic.com.mx
*.the-electroclassic.com.mx
localhost/*
```

The above should cover both the site and locally.  
However if you're testing locally by just running the page directly to the browser (ie. `file:///C:/.../YTV/testing.html`) you will have to set the referrals to allow any (leave it blank). Just remember to change it back when you're done testing locally!  

Also note when changing referrers sometimes it can take a minute or 2 to update on their end.

I also tested the channel in your link to make sure there was additional errors you may encounter and it worked correctly. So I hope this is enough information to solve the issue!

**Comment by TheElectroclassics** [comment]
Actually, I'm testing it on my website, since I thought that'll be the best way to do it, I don't have IP's marked on the console, but two websites, here they are:
![api](https://cloud.githubusercontent.com/assets/7582546/8145498/b4981a6c-11cf-11e5-9da5-a442c261499a.png)
and it's not working, when you suggested deleting them for local testing, well, nothing comes. I don't know, what else I can do

**Comment by mvmkr** [comment]
@Giorgio003 When you'll get your hands on WP plugin, let me know if you need some testers ... i'll gladly help with this.

@TheElectroclassics  If you configured api properly, here's the solution for you...
Follow next steps:

from html page, remove: user: 'CEDATOficial',
and uncomment : channelid: 'UCg44zX42-GjMr5XqyK3RmsQ',  
also you can add a specific playlist like this: playlist: 'your_playlist_id',

In case with playlist you don't even need channelid.
Hope this works for you as it worked for me.

**Comment by Giorgio003** [comment]
@mvmkr I'll keep that in mind!  

Also I believe that channel ID is the google fiber one, so unrelated to `CEDATOficial`.  

@TheElectroclassics try using this for your referrers:

```
the-electroclassic.com.mx
*.the-electroclassic.com.mx
[second_site].com.mx
*.[second_site].com.mx
```

This will cover all of the domain and sub-domains. If you have no need to cover sub-domains, then the following should also work.

```
the-electroclassic.com.mx
www.the-electroclassic.com.mx
[second_site].com.mx
www.[second_site].com.mx
```

This will just cover the domains with and without the `www`. Hopefully that will work! I know when I was first setting up API's it took me a bit to figure out proper formatting to get it working. 
(Reference: https://developers.google.com/console/help/#whitelistingbyhost)

**Comment by TheElectroclassics** [comment]
Ok. Looks like I'm going to have lots of fun with Java xD

**Comment by TheElectroclassics** [comment]
Thanks for your support

**Comment by Giorgio003** [comment]
@TheElectroclassics 
Oh yeah, loads of fun haha. :stuck_out_tongue_closed_eyes: 
I'll take it you got everything sorted out and working correctly now?

**Comment by TheElectroclassics** [comment]
Not yet, I'm still trying to figure what is making my life a mess. Well,
right now I'm on my way home, so I'll check it there, it's going to be
awesome

**Comment by TheElectroclassics** [comment]
IT WORKED!!!!!!!!!!!!!!!!!!!!!!!!!! THANKS FOR YOUR SUPPORT :)

**Comment by TheElectroclassics** [comment]
Now it's time to make it work [here](http://the-electroclassic.com.mx/YTV/VIDEOSCEDAT.html)
This is a copy of an html from my second domain, I copied the script form testing.html and the .js/.css but nothing comes, I'm working on find the trouble, any ideas?

**Comment by TheElectroclassics** [comment]
Forget it, it worked, thanks again :)

**Comment by Giorgio003** [comment]
@TheElectroclassics glad to hear!

I took a quick look anyway, and a couple things visually related to the player that could be fixed. First off I noticed you have a fixed height (`height: 650px;`) while using responsive option which causes the video expand/shrink separate from the video list.  
For this you have two ways to go. Option 1 sticking with the responsive player and removing the set height from: 

``` css
// near the end of your videos.css
#frame,.description {
    align-content: center width:68%;
    height: 650px;
}
```

Unsure if the class `description` is used for anything else, but best to just remove `#frame,` from that line as the first statement is invalid (thus not being applied) and the height affects the player.  

Option 2 if you're looking to keep the fixed height is to disable/remove `responsive` option as this will allow the youtube player to adjust the height of the video automatically. However this will leave the player feeling squished on mobile resolutions.  

The text alignment is more a matter of preference, but the `body` css tag causes the player's text to align centered as well. 

``` css
// throw somewhere in videos.css
#frame {
    text-align: left;
}
```

Quick fix for left aligned text to look similar to the demos. Unless you prefer it centered then no worries there. :)  

Additionally you can remove extra options such as `shuffleList: false, browsePlaylists: false,`, as they are false by default; but I assume this was just a rough draft till you got the player working correctly so I'll leave it at that.  
Good luck! :+1:
